function changeLanguage() {

    if ($('#welcome').text() == 'Welcome!') { //converte para portugues
        $('#welcome').text("Bem vindos!")
        $('#nav_about').text("sobre")
        $('#nav_soft-skills').text("personalidade")
        $('#nav_hard-skills').text("conhecimentos")
        $('#nav_projects').text("projetos")
        $('#introduction').text("Eu sou Izabella Santos, uma desenvolvedora web fullstack. Esse é o lugar no qual você pode ver um pouco mais sobre mim e meu trabalho. Eu amo criar projetos por causa de todos os sentimentos que eles me causam. Você pode entrar em contato comigo pelos links abaixo.")
        $('#soft-skills').text("Traços de personalidade")
        $('#team_work').text('Trabalho em Equipe')
        $('#team_description').text("A chave para aprender mais e compartilhar soluções. Pessoas tem sempre algo diferente para nos ensinar e eu amo aprender tudo isso.")
        $('#communication').text('Comunicação')
        $('#communication_description').text('Comunicação é uma das minhas melhores qualidades, eu sempre fui apaixonada em estar em contato com as pessoas e entender o que eles querem.')
        $('#organization').text('Organização')
        $('#organization_description').text('O método que te dá uma noção completa de suas tarefas. Eu sempre tento dar a importância certa para cada tarefa que eu preciso realizar.')
        $('#hard-skills-title').text('Conhecimentos técnicos')
        $('#database').text('Banco de dados')
        $('#backend').text('Back-end')
        $('#tools').text('Ferramentas')
        $('#frontend').text('Front-end')
        $('#projects-title').text('Projetos')
        $('#sephirot_description').text('Trabalho de Conclusão do CEFET-MG. É um projeto de jogo 2D no qual você pode aprender sobre diferentes matérias do ensino médio, como física e química. Ele foi desenvolvido na plataforma Unity, utilizando C# e assets gratuitos da loja da Unity.')
        $('#viacep_title').text('Formulário API ViaCEP')
        $('#viacep_description').text("Esse projeto foi usado para aprender um pouco mais sobre API's. Ele é um formulário com design Bootstrap, o qual coleta todas as informações via PHP e salva elas no banco de dados MySQL.")

    } else { //converte para ingles
        $('#welcome').text("Welcome!")
        $('#nav_about').text("about")
        $('#nav_soft-skills').text("soft skills")
        $('#nav_hard-skills').text("hard skills")
        $('#nav_projects').text("projects")
        $('#introduction').text('I am Izabella Júlia dos Santos, a web fullstack dev. This is my place for you to know a little bit more about me and my kind of work. I love creating my projects due to the satisfying feeling I get. You can get in touch with me in my social medias and my email below.')
        $('#soft-skills').text("Soft skills")
        $('#team_work').text('Team Work')
        $('#team_description').text("The key to learn more and share solutions. People have always something different to teach us and I love hearing everything.")
        $('#communication').text('Communication')
        $('#communication_description').text('Communication is one of my best qualities, I have always loved to be in touch with people and I desire to undestand what they want.')
        $('#organization').text('Organization')
        $('#organization_description').text('The method which provides you a complete notion about your tasks.I alwyas try to give the right importance for each task I have to do.')
        $('#hard-skills-title').text('Hard skills')
        $('#database').text('Database')
        $('#backend').text('Back-end')
        $('#tools').text('Tools')
        $('#frontend').text('Front-end')
        $('#projects-title').text('Projects')
        $('#sephirot_description').text('CEFET-MG final assignment. It is a 2D game project where you can learn about a lot of different high schools subjects, such as physics and chemistry.It has been developed in Unity Engine, with C# and free assets found in the Unity store.')
        $('#viacep_description').text("This project was used to learn a little bit more about API's. It is a design Bootstrap form, which collect all the information by PHP and save it in a MySQL database.")
        $('#viacep_title').text('API ViaCEP form')
    }

}